timing: True
debug: False
stop_at_error: False

likelihood:
  lsst_y1.lsst_cosmic_shear:
    path: ./external_modules/data/lsst_y1
    data_file: LSST_Y1_no_scale_cut.dataset
    print_datavector: False
    kmax_boltzmann: 5.0

params:
  logA:
    prior:
      min: 1.61
      max: 3.91
    ref:
      dist: norm
      loc: 3.0675
      scale: 0.05
    proposal: 0.05
    latex: \log(10^{10} A_\mathrm{s})
    drop: true
  As:
    value: 'lambda logA: 1e-10*np.exp(logA)'
    latex: A_\mathrm{s}
  ns:
    prior:
      min: 0.87
      max: 1.07
    ref:
      dist: norm
      loc: 0.97
      scale: 0.01
    proposal: 0.01
    latex: n_\mathrm{s}
  H0:
    prior:
      min: 55
      max: 91
    ref:
      dist: norm
      loc: 69
      scale: 3
    proposal: 3
    latex: H_0
  omegab:
    prior:
      min: 0.03
      max: 0.07
    ref:
      dist: norm
      loc: 0.048
      scale: 0.003
    proposal: 0.003
    latex: \Omega_\mathrm{b}
    drop: true
  omegam:
    prior:
      min: 0.01
      max: 0.9
    ref:
      dist: norm
      loc: 0.3
      scale: 0.02
    proposal: 0.02
    latex: \Omega_\mathrm{m}
    drop: true
  mnu:
    value: 0.06
  tau:
    value: 0.05
    latex: \tau_\mathrm{reio}
  omegal:
    latex: \Omega_\Lambda
  omegamh2:
    derived: 'lambda omegam, H0: omegam*(H0/100)**2'
    latex: \Omega_\mathrm{m} h^2
  omegabh2:
    value: 'lambda omegab, H0: omegab*(H0/100)**2'
    latex: \Omega_\mathrm{b} h^2
  omegach2:
    value: 'lambda omegam, omegab, mnu, H0: (omegam-omegab)*(H0/100)**2-(mnu*(3.046/3)**0.75)/94.0708'
    latex: \Omega_\mathrm{c} h^2
  omegan2:
    latex: \Omega_\mathrm{\\nu} h^2
  omegan:
    derived: 'lambda omegan2, H0: omegan2/((H0/100)**2)'
    latex: \Omega_\mathrm{\\nu}
  sigma8:
    latex: \sigma_8
  s8h5:
    derived: 'lambda sigma8, H0: sigma8*(H0*1e-2)**(-0.5)'
    latex: \sigma_8/h^{0.5}
  s8omegamp5:
    derived: 'lambda sigma8, omegam: sigma8*omegam**0.5'
    latex: \sigma_8 \Omega_\mathrm{m}^{0.5}
  s8omegamp25:
    derived: 'lambda sigma8, omegam: sigma8*omegam**0.25'
    latex: \sigma_8 \Omega_\mathrm{m}^{0.25}
  sigma8:
    latex: \sigma_8
  LSST_BARYON_Q1:
    value: 0.0
    latex: Q1_\mathrm{LSST}^1
  LSST_BARYON_Q2:
    value: 0.0
    latex: Q2_\mathrm{LSST}^2
  w:
    value: -1
    latex: w0
  #Galaxy bias, shear calibration, baryons do not enter emulation
  LSST_DZ_S1:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,LSST}^1
  LSST_DZ_S2:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,LSST}^2
  LSST_DZ_S3:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,LSST}^3
  LSST_DZ_S4:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,LSST}^4
  LSST_DZ_S5:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,LSST}^5
  LSST_A1_1:
    prior:
      min: -5
      max:  5
    ref:
      dist: norm
      loc: 0.5
      scale: 0.1
    proposal: 0.5
    # prior:
    #   min: 0
    #   max:  1
    # ref:
    #   dist: norm
    #   loc: 0.5
    #   scale: 0.1
    # proposal: 0.5
    latex: A_\mathrm{1-IA,LSST}^1
  LSST_A1_2:
    prior:
      min: -5
      max:  5
    ref:
      dist: norm
      loc: 0.
      scale: 0.1
    proposal: 0.5
    # prior:
    #   min: -2.0
    #   max:  2.0
    # ref:
    #   dist: norm
    #   loc: 0.
    #   scale: 0.1
    # proposal: 0.5
    latex: A_\mathrm{1-IA,LSST}^2
  LSST_A1_3:
    value: 0
    latex: A_\mathrm{1-IA,LSST}^3
  LSST_A1_4:
    value: 0
    latex: A_\mathrm{1-IA,LSST}^4
  LSST_A1_5:
    value: 0
    latex: A_\mathrm{1-IA,LSST}^5
  LSST_A2_1:
    value: 0.0
    latex: A_\mathrm{2-IA,LSST}^1
  LSST_A2_2:
    value: 0.0
    latex: A_\mathrm{2-IA,LSST}^2
  LSST_A2_3:
    value: 0
    latex: A_\mathrm{2-IA,LSST}^3
  LSST_A2_4:
    value: 0
    latex: A_\mathrm{2-IA,LSST}^4
  LSST_A2_5:
    value: 0
    latex: A_\mathrm{2-IA,LSST}^5
  LSST_BTA_1:
    value: 0.0
    latex: A_\mathrm{BTA-IA,LSST}^1
  LSST_BTA_2:
    value: 0
    latex: A_\mathrm{BTA-IA,LSST}^2
  LSST_BTA_3:
    value: 0
    latex: A_\mathrm{BTA-IA,LSST}^3
  LSST_BTA_4:
    value: 0
    latex: A_\mathrm{BTA-IA,LSST}^4
  LSST_BTA_5:
    value: 0
    latex: A_\mathrm{BTA-IA,LSST}^5
  #shear calibration need to be set to 0 for training emulators
  LSST_M1:
    value: 0.0
    latex: m_\mathrm{LSST}^1
  LSST_M2:
    value: 0.0
    latex: m_\mathrm{LSST}^2
  LSST_M3:
    value: 0.0
    latex: m_\mathrm{LSST}^3
  LSST_M4:
    value: 0.0
    latex: m_\mathrm{LSST}^4
  LSST_M5:
    value: 0.0
    latex: m_\mathrm{LSST}^5
  LSST_BARYON_Q1:
    value: 0.0
    latex: Q1_\mathrm{LSST}^1
  LSST_BARYON_Q2:
    value: 0.0
    latex: Q2_\mathrm{LSST}^2
  LSST_BARYON_Q3:
    value: 0.0
    latex: Q3_\mathrm{LSST}^3
  LSST_BARYON_Q4:
    value: 0.0
    latex: Q4_\mathrm{LSST}^4


theory:
  camb:
    path: ./external_modules/code/CAMB
    stop_at_error: False
    use_renames: True
    extra_args:
      halofit_version: takahashi
      AccuracyBoost: 1.15
      lens_potential_accuracy: 1.0
      num_massive_neutrinos: 1
      nnu: 3.046
      dark_energy_model: ppf
      accurate_massive_neutrino_transfers: false
      k_per_logint: 20

emulator:
  io:
      savedir: ./projects/lsst_y1/emulator_output/models     
      save_train_data: true             
      save_intermediate_model: true
  training:
      dv_fid: ./projects/lsst_y1/data/dv1_lsst_y1_theory.modelvector
      chi_sq_cut: 1e+5
      n_train_iter: 1
      #n_lhs: 4800
      #n_lhs: 48 #KZ debug
      n_lhs: 100000
      #n_resample: 9600
      n_resample: 96 #KZ debug
      emu_type: nn
      batch_size: 10000
      n_epochs: 150
      do_PCA: true
      n_PCA: 780
  shear_calib:
      mask: ./projects/lsst_y1/data/emu_files/shear_calib_mask.npy
      prior_std: 0.005, 0.005, 0.005, 0.005, 0.005
  baryons:
      n_pcas_baryon: 0
      prior_Q1: -3., 12.
  sampling:
      scalecut_mask: ./projects/lsst_y1/data/lsst_3x2.mask
      #sampling here doesn't matter if n_train_iter=1, but still save here for comparison
      n_mcmc: 1000
      #n_mcmc: 10 #KZ debug
      n_emcee_walkers: 120
      n_burn_in: 500
      #n_burn_in: 0 #KZ debug
      n_thin: 5
      #n_thin: 1 #KZ debug
      temper0: 0.05
      temper0: 0.99 #KZ debug
      temper_increment: 0.1
  probe: 'cosmic_shear'


output: ./projects/lsst_y1/chains/train_emulator